apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: minimal-cluster
spec:
  crVersion: 1.14.0
  secretsName: minimal-cluster-secrets
  allowUnsafeConfigurations: true
  upgradeOptions:
    apply: disabled
    schedule: "0 4 * * *"
  pxc:
    size: 1
    image: percona/percona-xtradb-cluster:8.0.35-27.1
    autoRecovery: true
    serviceAccountName: percona-xtradb-cluster-operator
    imagePullPolicy: IfNotPresent
    configuration: |
      [mysqld]
      wsrep_debug=CLIENT
      wsrep_provider_options="gcache.size=1G; gcache.recover=yes"
      innodb_buffer_pool_size=50M
      innodb_log_file_size=1G
      [sst]
      xbstream-opts=--decompress
      [xtrabackup]
      compress=lz4
    resources:
      requests:
        memory: 1G
        cpu: 200m
    affinity:
      advanced:
        nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: instance
                  operator: NotIn
                  values:
                  - spot
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 10G
  haproxy:
    enabled: true
    size: 1
    image: percona/percona-xtradb-cluster-operator:1.14.0-haproxy
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
    affinity:
      advanced:
        nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: instance
                  operator: NotIn
                  values:
                  - spot
  logcollector:
    enabled: false
    image: percona/percona-xtradb-cluster-operator:1.14.0-logcollector

  backup:
    image: percona/percona-xtradb-cluster-operator:1.14.0-pxc8.0-backup-pxb8.0.35
    serviceAccountName: percona-xtradb-cluster-operator
    storages:
      s3-do-bucket:
        type: s3
        verifyTLS: true
        resources:
          requests:
            memory: 0.1G
            cpu: 100m
          limits:
            memory: 1G
            cpu: 700m
        s3:
          bucket: backup-mysql-oprator-test
          credentialsSecret: backup-minimal-cluster-cerd-s3
          region: sgp1
          endpointUrl: https://sgp1.digitaloceanspaces.com
    schedule:
      - name: "daily-backup"
        schedule: "*/10 * * * *"
        keep: 2
        storageName: s3-do-bucket